<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HospitalManagement.BusinessLayer\HospitalManagement.BusinessLayer.csproj" />
    <ProjectReference Include="..\HospitalManagement.Data\HospitalManagement.Data.csproj" />
    <ProjectReference Include="..\HospitalManagement.Entities\HospitalManagement.Entities.csproj" />
    <ProjectReference Include="..\HospitalManagement.Utilities\HospitalManagement.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\HospitalManagement\Common\" />
    <Folder Include="Controllers\HospitalManagement\Reports\" />
    <Folder Include="Controllers\HospitalManagement\Transactions\" />
    <Folder Include="wwwroot\dist\" />
  </ItemGroup>

</Project>
